# Generated by Django 4.2 on 2026-05-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('drink', 'Напитка/Храна'), ('equipment', 'Екипировка'), ('service', 'Услуга (Наем, Наплитане)'), ('product', 'Стока')], default='product', max_length=20, verbose_name='Категория'),
        ),
    ]
