# Generated by Django 4.2 on 2026-05-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('drink', 'Напитка/Храна'), ('equipment', 'Екипировка'), ('service', 'Услуга (Наем, Наплитане)'), ('training', 'Тренировка'), ('product', 'Стока')], default='product', max_length=20, verbose_name='Категория'),
        ),
    ]
