# Generated by Django 4.2 on 2026-05-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('drink', 'Напитка/Храна'), ('game', 'Игра'), ('rental', 'Наем'), ('stringing', 'Наплитане'), ('training', 'Тренировка'), ('product', 'Стока')], default='product', max_length=20, verbose_name='Категория'),
        ),
    ]
