# Generated by Django 4.2 on 2026-05-24 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_sale_payment_method_cashtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на приключване')),
                ('sales_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оборот')),
                ('cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='В брой')),
                ('card_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='С карта')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Наличност каса')),
                ('attendance', models.IntegerField(default=0, verbose_name='Посещаемост')),
                ('comment', models.CharField(blank=True, default='', max_length=200, verbose_name='Коментар')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Касиер')),
            ],
        ),
    ]
