# Generated by Django 4.2 on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_shiftclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftclose',
            name='shift_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало на смяна'),
        ),
        migrations.AddField(
            model_name='shiftclose',
            name='sales_count',
            field=models.IntegerField(default=0, verbose_name='Брой продажби'),
        ),
        migrations.AddField(
            model_name='shiftclose',
            name='cash_transactions_count',
            field=models.IntegerField(default=0, verbose_name='Брой касови движения'),
        ),
        migrations.AddField(
            model_name='shiftclose',
            name='report_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Подробен отчет'),
        ),
    ]
