# Generated by Django 4.2 on 2026-05-24

from django.db import migrations


def make_admin_role_staff(apps, schema_editor):
    User = apps.get_model('bookings', 'User')
    User.objects.filter(role='admin').update(is_staff=True)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_shiftclose_report_snapshot'),
    ]

    operations = [
        migrations.RunPython(make_admin_role_staff, migrations.RunPython.noop),
    ]
