# Generated by Django 4.2 on 2026-06-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_user_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Клиент'), ('trainer', 'Треньор'), ('employee', 'Служител'), ('accounting', 'Счетоводство'), ('admin', 'Администратор')], default='customer', max_length=10),
        ),
    ]
