# Generated by Django 4.2 on 2026-06-01 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Разход')),
                ('category', models.CharField(choices=[('inventory', 'Доставка'), ('utilities', 'Консумативи'), ('rent', 'Наем'), ('maintenance', 'Ремонт'), ('salary', 'Заплати'), ('supplier', 'Доставчик'), ('other', 'Други')], default='other', max_length=20, verbose_name='Категория')),
                ('payment_method', models.CharField(choices=[('cash', 'В брой'), ('card', 'С карта'), ('bank', 'Банков превод')], default='cash', max_length=10, verbose_name='Начин на плащане')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('comment', models.CharField(blank=True, default='', max_length=200, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Създадено от')),
            ],
        ),
    ]
